# Generated by Django 5.2.6 on 2025-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
