# Generated by Django 5.2.6 on 2025-10-27 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 10, 28, 14, 14, 46, 779485, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
