# Generated by Django 5.2.6 on 2025-10-27 14:54

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_alter_invoice_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="paid",
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("overdue", "Overdue"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                blank=True, default=invoices.models.default_due_date, null=True
            ),
        ),
    ]
